name: feature-flipper
version: '0.2.1.2'
synopsis: A minimally obtrusive feature flag library
description: A minimally obtrusive feature flag library
category: Web
author: Todd Mohney
maintainer: toddmohney@gmail.com
copyright: 2017 Todd Mohney
license: MIT
github: toddmohney/flipper
extra-source-files:
- README.md

dependencies:
- base >=4.8 && <5
- bytestring
- containers
- digest
- mtl
- text

library:
  source-dirs: src
  default-extensions:
  - OverloadedStrings
  exposed-modules:
  - Control.Flipper
  - Control.Flipper.Types
  - Control.Flipper.Adapters.Memory
  ghc-options:
  - -Wall
  - -freverse-errors
  - -fwarn-unused-binds
  - -fwarn-unused-imports
  - -fwarn-unused-matches

tests:
  feature-flipper-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - OverloadedStrings
    dependencies:
    - feature-flipper
    - hspec
    other-modules:
    - Control.FlipperSpec
